cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('update/<item_id>/', views.update_cart, name='update_cart'),
    path('remove/<item_id>/', views.remove_cart, name='remove_cart'),
]

panther_fitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('subscriptions/', include('subscriptions.urls')),
    path('lessons/', include('lessons.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    original_cart = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput) 

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'black-text'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from cart.contexts import cart_contents
from .models import Product, Category
from .forms import ProductForm
from profiles.models import UserProfile
# Create your views here.


def check_user(request):
    """ check if user has fitness programme """
    if request.user.is_authenticated:
        profile = get_object_or_404(UserProfile, user=request.user)
        orders = profile.orders.all()
        for order in orders:
            line_items = order.lineitems.all()
            for item in line_items:
                if item.product.name == 'Fitness Programme':
                    return True
        return False
    else:
        return 'AnonymousUser'


def all_products(request):
    """ A view to show all products and sorting search queries. """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None
    anon_message = 'Register to Buy Fitness Pogramme'

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(
                description__icontains=query)
            products = products.filter(queries)

    #  check if user has programme
    has_programme = check_user(request)
    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
        'has_programme': has_programme,
        'anon_message': anon_message,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show a single products detail. """

    product = get_object_or_404(Product, pk=product_id)

    current_cart = cart_contents(request)
    cart_items = current_cart['cart_items']
    lesson_in_cart = False

    for item in cart_items:
        if item["item_id"]:
            lesson_in_cart = True

    context = {
        'product': product,
        'lesson_in_cart': lesson_in_cart,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can add a product.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can edit a product.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Failed to update product. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only store owners can delete a product.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %} {% load static %} {% block page_header %}
<div class="container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %} {% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col s12 m6">
            <h2 class="red-text darken-4 center-align">Product Management</h2>
            <h5 class="black-text center-align"><small>Add a Product</small></h5>
        </div>
    </div>

    <div class="row card-panel">
        <div class="col s12 m6">
            <form method="POST" action="{% url 'add_product' %}" class="add-product-from" style="margin-bottom: 2px;" enctype="multipart/form-data">
                {% csrf_token %} {% for field in form %} {% if field.name != 'image' %} {{ field | as_crispy_field }} {% else %} {{ field }} {% endif %} {% endfor %}
                <div class="right">
                    <a href="{% url 'products' %}" class="btn text-uppercase">Cancel</a>
                    <button class="btn btn-black" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %} {% block postloadjs %} {{ block.super }}
<script type="text/javascript">
    $("select").formSelect();
    $("#new-image").change(function () {
        var file = $("#new-image")[0].files[0];
        $("#filename").text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %} {% load static %} {% block page_header %}
<div class="container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %} {% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col s12 m6">
            <h2 class="red-text darken-4 center-align">Product Management</h2>
            <h5 class="black-text center-align"><small>Edit a Product</small></h5>
        </div>
    </div>

    <div class="row card-panel">
        <div class="col s12 m6">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="add-product-from" style="margin-bottom: 2px;" enctype="multipart/form-data">
                {% csrf_token %} {% for field in form %} {% if field.name != 'image' %} {{ field | as_crispy_field }} {% else %} {{ field }} {% endif %} {% endfor %}
                <div class="right">
                    <a href="{% url 'products' %}" class="btn text-uppercase">Cancel</a>
                    <button class="btn btn-black" type="submit">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %} {% block postloadjs %} {{ block.super }}
<script type="text/javascript">
    $("select").formSelect();
    $("#new-image").change(function () {
        var file = $("#new-image")[0].files[0];
        $("#filename").text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %} {% load static %} {% block page_header %}
<div class="container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %} {% block content %}
<div class="overlay"></div>
<div class="product-detail-container">
    <div class="row">
        <div class="col-12">
            <a href="{% url 'products' %}" class="arrow-icon">
                <i class="fas fa-arrow-left">Back to shopping</i>
            </a>
        </div>
    </div>
    <div class="row card-panel">
        <div class="col m7">
            {% if product.image %}
            <a href="{{ product.image.url }}" target="_blank">
                <img class="img-detail" src="{{ product.image.url }}" alt="{{ product.name }}" />
            </a>
            {% else %}
            <a href="#">
                <img src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}" />
            </a>
            {% endif %}
        </div>
        {% if request.user.is_superuser %}
        <small style="padding-left: 10px;">
            <a class="black-text" href="{% url 'edit_product' product.id %}">Edit</a> |
            <a class="red-text" href="{% url 'delete_product' product.id %}">Delete</a>
        </small>
        {% endif %}
        <div class="col m5">
            <h3 class="black-text darken-4">{{ product.name }}</h3>
            <p>
                {% if product.rating %}
                <small class="text-muted"><i class="fas fa-star"></i>{{ product.rating }} / 5</small>
                {% else %}
                <small class="text-muted">No Rating</small>
                {% endif %}
            </p>
            <p>{{ product.description }}</p>
            {% if product.category %}
            <p class="cat-tag">
                <a class="text-muted black-text" href="{% url 'products' %}?category={{ product.category.name }}"> <i class="fas fa-tag"></i>{{ product.category.friendly_name }} </a>
            </p>
            {% endif %}
            <h4>£{{ product.price }}</h4>
            <form class="form" action="{% url 'add_to_cart' product.id %}" method="POST">
                {% csrf_token %} {% with product.has_sizes as s %} {% if s %}
                <div class="input-field col s12" style="width: 75%;">
                    <p>Size:</p>
                    <select name="product_size" id="id_product_size">
                        <option value="xs">XS</option>
                        <option value="s">S</option>
                        <option value="m" selected>M</option>
                        <option value="l">L</option>
                        <option value="xl">XL</option>
                    </select>
                </div>
                {% endif %}
                <div class="col s12" style="width: 75%;">
                    <p>Quantity</p>
                    <div class="input-field decrement-qty" data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}"></div>
                    <input class="form-control qty_input" type="number" name="quantity" value="1" min="1" max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}" />
                    <div class="input-field increment-qty" data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}"></div>
                </div>
                <div class="col s12">
                    <input type="submit" class="btn btn-cart" value="Add to Cart" />
                </div>
                <input type="hidden" name="redirect_url" value="{{ request.path }}" />
                {% endwith %}
            </form>
        </div>
    </div>
</div>

{% endblock %} {% block postloadjs %}
<script type="text/javascript">
    $("select").formSelect();
</script>
{{ block.super }} {% include 'products/includes/quantity_input_script.html' %} {% endblock %}

products/templates/products/products.html
{% extends "base.html" %} {% load static %} {% block page_header %}
<nav class="nav-extended text-shadow black">
    <div class="nav-wrapper">
        <ul class="pro-cat">
            <li><a class="cat" href="{% url 'products' %}">All Products</a></li>
            <li><a class="cat" href="{% url 'products' %}?category=activewear">Activewear</a></li>
            <li><a class="cat" href="{% url 'products' %}?category=equipment">Equipment</a></li>
            <li><a class="cat" href="{% url 'products' %}?category=clearance">Clearance</a></li>
            <li><a class="cat" href="{% url 'products' %}?category=special_offers">Special Offers</a></li>
            <li><a class="cat" href="{% url 'products' %}?category=new_arrivals">New Arrivals</a></li>
            <li><a class="cat" href="{% url 'products' %}?category=memberships">Memberships</a></li>
        </ul>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="red-text darken-4 center-align">Products</h2>
        </div>
    </div>
</div>
{% endblock %} {% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col s12 m3">
            <h4>Search</h4>
            <form method="GET" action="{% url 'products' %}">
                <div class="input-group">
                    <input class="form-control border search-box" type="text" name="q" placeholder="Search our products" />
                    <div class="input-group-append">
                        <button class="form-control btn border search-btn" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col s12 m3 right">
            <!-- Dropdown Trigger -->
            <a class="dropdown-trigger btn sort-btn" href="#" data-target="dropdown1">Sort By:</a>

            <!-- Dropdown Structure -->
            <ul id="dropdown1" class="dropdown-content">
                <li><a href="{% url 'products' %}?sort=price&direction=asc">Price (low to high)</a></li>
                <li><a href="{% url 'products' %}?sort=price&direction=desc">Price (high to low)</a></li>
                <li><a href="{% url 'products' %}?sort=rating&direction=asc">Rating (low to high)</a></li>
                <li><a href="{% url 'products' %}?sort=rating&direction=desc">Rating (high to low)</a></li>
                <li><a href="{% url 'products' %}?sort=name&direction=asc">Name (A-Z)</a></li>
                <li><a href="{% url 'products' %}?sort=name&direction=desc">Name (Z-A)</a></li>
                <li><a href="{% url 'products' %}?sort=category&direction=asc">Category (A-Z)</a></li>
                <li><a href="{% url 'products' %}?sort=category&direction=desc">Category (Z-A)</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <div class="col s12 m3">
        <p class="text-muted center">
            {% if search_term or current_categories or current_sorting != 'None_None' %}
            <span class="small"><a class="red-text darken-4" href="{% url 'products' %}">All Products</a> | </span>
            {% endif %} {{ products | length }} Products{% if search_term %} found for <strong>"{{ search_term }}"</strong>{% endif %}
        </p>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        {% for product in products %}
        <div class="col s12 m4">
            <div class="card">
                {% if product.image %}
                <div class="card-image">
                    <a href="{% url 'product_detail' product.id %}">
                        <img class="img-products" src="{{ product.image.url }}" alt="{{ product.name }}" />
                    </a>
                    {% else %}
                    <a href="{% url 'product_detail' product.id %}">
                        <img src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}" />
                    </a>
                    {% endif %}
                </div>
                <div class="card-content">
                    <p style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">{{ product.name }}</p>
                    <p style="font-size: 30px;">£{{ product.price }}</p>
                    {% if product.rating %}
                    <small class="text-muted"><i class="fas fa-star"></i>{{ product.rating }} / 5</small>
                    {% else %}
                    <small class="text-muted">No Rating</small>
                    {% endif %} {% if product.category %}
                    <p class="cat-tag">
                        <a class="text-muted black-text" href="{% url 'products' %}?category={{ product.category.name }}"> <i class="fas fa-tag"></i>{{ product.category.friendly_name }} </a>
                    </p>
                    {% endif %} {% if request.user.is_superuser %}
                    <small>
                        <a class="black-text" href="{% url 'edit_product' product.id %}">Edit</a> |
                        <a class="red-text" href="{% url 'delete_product' product.id %}">Delete</a>
                    </small>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="fixed-action-btn">
    <a href="{% url 'products' %}" class="btn-floating btn-large btn">
        <i class="fas fa-arrow-up"></i>
    </a>
</div>
{% endblock %} {% block postloadjs %}
<script type="text/javascript">
    $(".sidenav").sidenav({ edge: "right" });
    $(".dropdown-trigger").dropdown();
</script>
{% endblock %}